set(LUX_CMAKE_TOOLSET_DIR           ${CMAKE_CURRENT_LIST_DIR})
set(LUX_CMAKE_COMMON_TOOLSET_DIR    ${LUX_CMAKE_TOOLSET_DIR}/common)
set(LUX_CMAKE_COMPONENT_TOOLSET_DIR ${LUX_CMAKE_TOOLSET_DIR}/component)